In [1]:
import numpy as np

In [2]:
board = np.zeros((20,20))

In [3]:
print(board)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [53]:
def unique_piece(possibility, pieces):
    # checks the same piece doesn't already exist
    transposedArray = np.transpose(possibility)
    possibilityTransformedArray = [possibility, transposedArray]
    np.rot90(possibility)
    possibilityTransformedArray.append(np.flip(transposedArray,axis=0))
    possibilityTransformedArray.append(np.flip(transposedArray,axis=1))
    possibilityTransformedArray.append(np.flip(possibility,axis=0))
    possibilityTransformedArray.append(np.flip(possibility,axis=1))
    isUnique = True
    for piece in pieces:
        notSame = np.any(np.all(piece == possibilityTransformedArray, axis=1))
        isUnique = isUnique and notSame
    return isUnique

In [25]:
def valid_piece(possibility):
    # for a piece to be valid, every square that makes it up must be touching another
    isValid = True
    dimensionMax = possibility.shape[0]
    for i in range(dimensionMax):
        for j in range(dimensionMax):
            if possibility[i][j] == 1:
                left = (i,j-1)
                right = (i,j+1)
                up = (i-1,j)
                down = (i+1,j)
                # left,right,up,down pieces
                adjacentIndexes = (left,right,up,down)
                isConnected = False
                for adjacentIndex in adjacentIndexes:
                    if adjacentIndex[0] < dimensionMax and adjacentIndex[0] >= 0 and adjacentIndex[1] < dimensionMax and adjacentIndex[1] >= 0:
                        isConnected = isConnected or (possibility[adjacentIndex[0]][adjacentIndex[1]] == 1)
                isValid = isValid and isConnected
    return isValid

True

In [34]:
def generate_possible(roots, prev_size):
    possibilities = []
    for root in roots:
        rootRaw = root.copy()
        root = np.zeros((prev_size+1,prev_size+1))
        root[0:prev_size,0:prev_size] = root[0:prev_size,0:prev_size] + rootRaw
        root_flat = root.flatten()
        empty = (prev_size+1)**2 - prev_size
        for i in range(0,empty):
            j = i
            array_index = 0
            while j != 0 or root_flat[array_index] == 1:
                if root_flat[array_index] == 0:
                    j -= 1
                array_index += 1
            possibility = root_flat.copy()
            possibility[array_index] = 1
            possibility = possibility.reshape((prev_size+1,prev_size+1))
            possibilities.append(possibility)
    return possibilities

generate_possible(np.ones((1,1)),1)

[array([[1., 1.],
        [0., 0.]]),
 array([[1., 0.],
        [1., 0.]]),
 array([[1., 0.],
        [0., 1.]])]

In [47]:
pieces = [np.ones((1,1))]
roots = [np.ones((1,1))]
newRoots = []
possibilities = generate_possible(roots,1)
for possibility in possibilities:
    if unique_piece(possibility, pieces) and valid_piece(possibility):
        pieces.append(possibility)
        newRoots.append(possibility)
print(pieces)

[[1. 1.]
 [0. 0.]]
[[1. 0.]
 [1. 0.]]
[[1. 0.]
 [0. 1.]]
[array([[1.]]), array([[1., 1.],
       [0., 0.]]), array([[1., 0.],
       [1., 0.]])]


In [59]:
def nextShapes(roots, prevSize):
    pieces = []
    if prevSize < 3:
        possibilities = generate_possible(roots,prevSize)
        for possibility in possibilities:
            if unique_piece(possibility, pieces) and valid_piece(possibility):
                pieces.append(possibility)
        pieces = pieces + nextShapes(pieces, prevSize + 1)
    return pieces

blokusPieces = nextShapes(np.ones((1,1)),1)


In [62]:
blokusPieces

[array([[1., 1.],
        [0., 0.]]),
 array([[1., 0.],
        [1., 0.]]),
 array([[1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 0.],
        [1., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 0.],
        [0., 1., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 0.],
        [1., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 0., 0.],
        [1., 1., 0.],
        [0., 0., 0.]]),
 array([[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])]